// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaffList.Database;

namespace StaffList.Database.Migrations
{
    [DbContext(typeof(AppMSSQLDbContext))]
    partial class AppMSSQLDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StaffList.Domain.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MaternityLeave")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Birthday = new DateTime(1981, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            FullName = "Иванов Иван Иванович",
                            MaternityLeave = false,
                            Position = "Инженер"
                        },
                        new
                        {
                            ID = 2,
                            Birthday = new DateTime(1981, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            FullName = "Иванова Инна Ивановна",
                            MaternityLeave = true,
                            Position = "Инженер"
                        },
                        new
                        {
                            ID = 3,
                            Birthday = new DateTime(1981, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            FullName = "Петров Петр Петрович",
                            MaternityLeave = true,
                            Position = "Инженер"
                        },
                        new
                        {
                            ID = 4,
                            Birthday = new DateTime(1981, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            FullName = "Петрова Полина Петровна",
                            MaternityLeave = false,
                            Position = "Инженер"
                        },
                        new
                        {
                            ID = 5,
                            Birthday = new DateTime(1981, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            FullName = "Егоров Устин Евсеевич",
                            MaternityLeave = false,
                            Position = "Старший инженер"
                        },
                        new
                        {
                            ID = 6,
                            Birthday = new DateTime(1981, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            FullName = "Морозова Аурелия Георгиевна",
                            MaternityLeave = true,
                            Position = "Старший инженер"
                        },
                        new
                        {
                            ID = 7,
                            Birthday = new DateTime(1981, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            FullName = "Наумов Модест Лаврентьевич",
                            MaternityLeave = true,
                            Position = "Старший инженер"
                        },
                        new
                        {
                            ID = 8,
                            Birthday = new DateTime(1981, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            FullName = "Шестакова Кира Митрофановна",
                            MaternityLeave = true,
                            Position = "Старший инженер"
                        },
                        new
                        {
                            ID = 9,
                            Birthday = new DateTime(1981, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            FullName = "Жуков Альберт Германнович",
                            MaternityLeave = false,
                            Position = "Ведущий инженер"
                        },
                        new
                        {
                            ID = 10,
                            Birthday = new DateTime(1981, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            FullName = "Гусева Наталья Арсеньевна",
                            MaternityLeave = true,
                            Position = "Ведущий инженер"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
